### ISSUE TITLE
Update to PHP 7.3

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#174] opened 2020-02-18 14:41 UTC
https://github.com/femiwiki/base/commit/874816f3204d0ce8216b2058d55202b117023246 에서 진행중

**Comment by lens0021** [comment] 2020-02-18 14:44
Closed as duplicate of https://github.com/femiwiki/docker-mediawiki/issues/345

**Closed by lens0021** 2020-02-18 14:44 UTC
